package com.educareapps.jsonreader.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ALL_GRID".
 */
public class AllGrid {

    private Long id;
    private Long userId;
    private long taskPackId;
    private int lessonNumber;
    /** Not-null value. */
    private String type;
    /** Not-null value. */
    private String description;
    private boolean status;

    public AllGrid() {
    }

    public AllGrid(Long id) {
        this.id = id;
    }

    public AllGrid(Long id, Long userId, long taskPackId, int lessonNumber, String type, String description, boolean status) {
        this.id = id;
        this.userId = userId;
        this.taskPackId = taskPackId;
        this.lessonNumber = lessonNumber;
        this.type = type;
        this.description = description;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public long getTaskPackId() {
        return taskPackId;
    }

    public void setTaskPackId(long taskPackId) {
        this.taskPackId = taskPackId;
    }

    public int getLessonNumber() {
        return lessonNumber;
    }

    public void setLessonNumber(int lessonNumber) {
        this.lessonNumber = lessonNumber;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getDescription() {
        return description;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescription(String description) {
        this.description = description;
    }

    public boolean getStatus() {
        return status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

}
