package com.educareapps.jsonreader.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DAILY_TBL".
 */
public class DailyTbl {

    private Long id;
    private long userId;
    private Long greenTaskPackId;
    private Long blueTaskPackId;
    private Long pinkTaskPackId;
    private Long purpleTaskPackId;
    private Long orangeTaskPackId;
    private Long yellowTaskPackId;

    public DailyTbl() {
    }

    public DailyTbl(Long id) {
        this.id = id;
    }

    public DailyTbl(Long id, long userId, Long greenTaskPackId, Long blueTaskPackId, Long pinkTaskPackId, Long purpleTaskPackId, Long orangeTaskPackId, Long yellowTaskPackId) {
        this.id = id;
        this.userId = userId;
        this.greenTaskPackId = greenTaskPackId;
        this.blueTaskPackId = blueTaskPackId;
        this.pinkTaskPackId = pinkTaskPackId;
        this.purpleTaskPackId = purpleTaskPackId;
        this.orangeTaskPackId = orangeTaskPackId;
        this.yellowTaskPackId = yellowTaskPackId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public Long getGreenTaskPackId() {
        return greenTaskPackId;
    }

    public void setGreenTaskPackId(Long greenTaskPackId) {
        this.greenTaskPackId = greenTaskPackId;
    }

    public Long getBlueTaskPackId() {
        return blueTaskPackId;
    }

    public void setBlueTaskPackId(Long blueTaskPackId) {
        this.blueTaskPackId = blueTaskPackId;
    }

    public Long getPinkTaskPackId() {
        return pinkTaskPackId;
    }

    public void setPinkTaskPackId(Long pinkTaskPackId) {
        this.pinkTaskPackId = pinkTaskPackId;
    }

    public Long getPurpleTaskPackId() {
        return purpleTaskPackId;
    }

    public void setPurpleTaskPackId(Long purpleTaskPackId) {
        this.purpleTaskPackId = purpleTaskPackId;
    }

    public Long getOrangeTaskPackId() {
        return orangeTaskPackId;
    }

    public void setOrangeTaskPackId(Long orangeTaskPackId) {
        this.orangeTaskPackId = orangeTaskPackId;
    }

    public Long getYellowTaskPackId() {
        return yellowTaskPackId;
    }

    public void setYellowTaskPackId(Long yellowTaskPackId) {
        this.yellowTaskPackId = yellowTaskPackId;
    }

}
