package com.educareapps.jsonreader.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.educareapps.jsonreader.dao.User;
import com.educareapps.jsonreader.dao.TaskPack;
import com.educareapps.jsonreader.dao.Task;
import com.educareapps.jsonreader.dao.Item;
import com.educareapps.jsonreader.dao.Result;
import com.educareapps.jsonreader.dao.AllGrid;
import com.educareapps.jsonreader.dao.Point;
import com.educareapps.jsonreader.dao.DailyTbl;

import com.educareapps.jsonreader.dao.UserDao;
import com.educareapps.jsonreader.dao.TaskPackDao;
import com.educareapps.jsonreader.dao.TaskDao;
import com.educareapps.jsonreader.dao.ItemDao;
import com.educareapps.jsonreader.dao.ResultDao;
import com.educareapps.jsonreader.dao.AllGridDao;
import com.educareapps.jsonreader.dao.PointDao;
import com.educareapps.jsonreader.dao.DailyTblDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig taskPackDaoConfig;
    private final DaoConfig taskDaoConfig;
    private final DaoConfig itemDaoConfig;
    private final DaoConfig resultDaoConfig;
    private final DaoConfig allGridDaoConfig;
    private final DaoConfig pointDaoConfig;
    private final DaoConfig dailyTblDaoConfig;

    private final UserDao userDao;
    private final TaskPackDao taskPackDao;
    private final TaskDao taskDao;
    private final ItemDao itemDao;
    private final ResultDao resultDao;
    private final AllGridDao allGridDao;
    private final PointDao pointDao;
    private final DailyTblDao dailyTblDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        taskPackDaoConfig = daoConfigMap.get(TaskPackDao.class).clone();
        taskPackDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        resultDaoConfig = daoConfigMap.get(ResultDao.class).clone();
        resultDaoConfig.initIdentityScope(type);

        allGridDaoConfig = daoConfigMap.get(AllGridDao.class).clone();
        allGridDaoConfig.initIdentityScope(type);

        pointDaoConfig = daoConfigMap.get(PointDao.class).clone();
        pointDaoConfig.initIdentityScope(type);

        dailyTblDaoConfig = daoConfigMap.get(DailyTblDao.class).clone();
        dailyTblDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        taskPackDao = new TaskPackDao(taskPackDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);
        itemDao = new ItemDao(itemDaoConfig, this);
        resultDao = new ResultDao(resultDaoConfig, this);
        allGridDao = new AllGridDao(allGridDaoConfig, this);
        pointDao = new PointDao(pointDaoConfig, this);
        dailyTblDao = new DailyTblDao(dailyTblDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(TaskPack.class, taskPackDao);
        registerDao(Task.class, taskDao);
        registerDao(Item.class, itemDao);
        registerDao(Result.class, resultDao);
        registerDao(AllGrid.class, allGridDao);
        registerDao(Point.class, pointDao);
        registerDao(DailyTbl.class, dailyTblDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        taskPackDaoConfig.getIdentityScope().clear();
        taskDaoConfig.getIdentityScope().clear();
        itemDaoConfig.getIdentityScope().clear();
        resultDaoConfig.getIdentityScope().clear();
        allGridDaoConfig.getIdentityScope().clear();
        pointDaoConfig.getIdentityScope().clear();
        dailyTblDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public TaskPackDao getTaskPackDao() {
        return taskPackDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

    public ResultDao getResultDao() {
        return resultDao;
    }

    public AllGridDao getAllGridDao() {
        return allGridDao;
    }

    public PointDao getPointDao() {
        return pointDao;
    }

    public DailyTblDao getDailyTblDao() {
        return dailyTblDao;
    }

}
