package com.educareapps.jsonreader.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "POINT".
 */
public class Point {

    private Long id;
    private Long userId;
    private Long taskPackId;
    private Integer lessonNumber;
    private String type;
    private String description;
    private Long packRT;
    private Long packDT;
    private Integer packPoint;
    private Integer errorSize;
    private Integer PackSize;
    private Integer PackAnsSize;
    private Long insertedDateMillis;

    public Point() {
    }

    public Point(Long id) {
        this.id = id;
    }

    public Point(Long id, Long userId, Long taskPackId, Integer lessonNumber, String type, String description, Long packRT, Long packDT, Integer packPoint, Integer errorSize, Integer PackSize, Integer PackAnsSize, Long insertedDateMillis) {
        this.id = id;
        this.userId = userId;
        this.taskPackId = taskPackId;
        this.lessonNumber = lessonNumber;
        this.type = type;
        this.description = description;
        this.packRT = packRT;
        this.packDT = packDT;
        this.packPoint = packPoint;
        this.errorSize = errorSize;
        this.PackSize = PackSize;
        this.PackAnsSize = PackAnsSize;
        this.insertedDateMillis = insertedDateMillis;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getTaskPackId() {
        return taskPackId;
    }

    public void setTaskPackId(Long taskPackId) {
        this.taskPackId = taskPackId;
    }

    public Integer getLessonNumber() {
        return lessonNumber;
    }

    public void setLessonNumber(Integer lessonNumber) {
        this.lessonNumber = lessonNumber;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getPackRT() {
        return packRT;
    }

    public void setPackRT(Long packRT) {
        this.packRT = packRT;
    }

    public Long getPackDT() {
        return packDT;
    }

    public void setPackDT(Long packDT) {
        this.packDT = packDT;
    }

    public Integer getPackPoint() {
        return packPoint;
    }

    public void setPackPoint(Integer packPoint) {
        this.packPoint = packPoint;
    }

    public Integer getErrorSize() {
        return errorSize;
    }

    public void setErrorSize(Integer errorSize) {
        this.errorSize = errorSize;
    }

    public Integer getPackSize() {
        return PackSize;
    }

    public void setPackSize(Integer PackSize) {
        this.PackSize = PackSize;
    }

    public Integer getPackAnsSize() {
        return PackAnsSize;
    }

    public void setPackAnsSize(Integer PackAnsSize) {
        this.PackAnsSize = PackAnsSize;
    }

    public Long getInsertedDateMillis() {
        return insertedDateMillis;
    }

    public void setInsertedDateMillis(Long insertedDateMillis) {
        this.insertedDateMillis = insertedDateMillis;
    }

}
